apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: card-api
  name: card-api-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: card-api
  type: LoadBalancer
status:
  loadBalancer: {}
