version: "3.8"
services:
    card_game:
        build:
            context: .
            dockerfile: $DOCKER_FILE
        container_name: $CONTAINER_NAME
        ports:
            - $CONTAINER_PORT:$CONTAINER_PORT