version: "3.8"
services:
    card_api:
        build:
            context: .
            dockerfile: $DOCKER_FILE
            args:
                BASE_IMAGE: $BASE_IMAGE
                BASE_IMAGE_TAG: $BASE_IMAGE_TAG
                USERNAME: $USERNAME
                APP_DIR: $APP_DIR
        container_name: $API_CONTAINER_NAME
        environment:
            MONGO_DB_PORT: ${MONGO_DB_PORT}
            MONGO_DATABASE: ${MONGO_DATABASE}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_CONTAINER_NAME: ${MONGO_CONTAINER_NAME}
        ports:
            - $API_CONTAINER_PORT:$API_CONTAINER_PORT
    mongo:
        image: mongo
        container_name: $MONGO_CONTAINER_NAME
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_DATABASE: ${MONGO_DATABASE}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh
