version: "3.8"
services:
    card_game:
        build:
            context: .
            dockerfile: $DOCKER_FILE
            args:
                BASE_IMAGE: $BASE_IMAGE
                BASE_IMAGE_TAG: $BASE_IMAGE_TAG
                USERNAME: $USERNAME
                APP_DIR: $APP_DIR
        container_name: $CONTAINER_NAME
        environment:
            MONGO_DB_PORT: ${MONGO_DB_PORT}
            MONGO_DATABASE: ${MONGO_DATABASE}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_CONTAINER_NAME: ${MONGO_CONTAINER_NAME}
        ports:
            - $CONTAINER_PORT:$CONTAINER_PORT
