apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
        - image: docker.io/mongo:latest
          name: mongo
          resources: {}
          env:
            - name: MONGO_DB_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: "carddb"
            - name: MONGO_INITDB_DATABASE
              value: "admin"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-password
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongo-init-script-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-init-script-volume
          configMap:
            name: mongo-init
            defaultMode: 0744

status: {}
