name: Python package

on: [push]

env:
  GKE_CLUSTER: card-api
  GKE_ZONE: us-east4-c
  INIT_MONGO: init_mongo.sh
  API_PORT: 8080
  API_EXPOSED_PORT: 80
  API_SERVICE_NAME: card-api-service

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Test with pytest
        run: |
          python -m pytest --cov-report term-missing --cov=card_api tests/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bernoussim/card_api:latest
          build-args: |
            BASE_IMAGE=python
            BASE_IMAGE_TAG=3.7.9-alpine
            USERNAME=carduser
            APP_DIR=card_game
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Get The GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Deploy
        run: |
          kubectl --namespace ${{ env.GKE_NAMESPACE }} create secret generic mongo-root-credentials --from-literal=mongo-root-username=${{ secrets.MONGO_INITDB_ROOT_USERNAME}} --from-literal=mongo-root-password=${{ secrets.MONGO_INITDB_ROOT_PASSWORD}}
          kubectl --namespace ${{ env.GKE_NAMESPACE }} create secret generic mongo-credentials --from-literal=mongo-username=${{ secrets.MONGO_USERNAME }} --from-literal=mongo-password=${{ secrets.MONGO_PASSWORD }}
          kubectl --namespace ${{ env.GKE_NAMESPACE }} create configmap mongo-init --from-file=i${{ env.INIT_MONGO }}
          kubeclt --namespace ${{ env.GKE_NAMESPACE }} apply -f mongo_deployment.yaml
          kubectl --namespace ${{ env.GKE_NAMESPACE }} expose deployment mongo --type=NodePort --name=mongo
          kubectl --namespace ${{ env.GKE_NAMESPACE }} apply -f card_api_deployment.yaml
          kubectl --namespace ${{ env.GKE_NAMESPACE }} expose deployment card-api --name=${{ env.API_SERVICE_NAME }} --type=LoadBalancer --port ${{ env.API_EXPOSED_PORT }} --target-port ${{ env.API_PORT}}
